FROM continuumio/miniconda3

#FROM python:3

# set the working directory
WORKDIR /docker_image

# copy all the files to the container
#COPY . .

# install dependencies
RUN conda install -c conda-forge pymdi pyyaml pandas python-graphviz

# define the port number the container should expose
#EXPOSE 5000

# run the command
#CMD ["ls"]

