language: cpp
python:
  - "3.6"
sudo: required
services:
  - docker

matrix:
  include:
    - os: linux
      before_install:
        - ./MDI_Mechanic/scripts/.travis/travis_before_install.sh
      install:
        - ./MDI_Mechanic/scripts/.travis/travis_install.sh
      before_script:
        - ./MDI_Mechanic/scripts/.travis/travis_before_script.sh
      script:
        - ./MDI_Mechanic/scripts/.travis/travis_script.sh
