language: cpp
python:
  - "3.6"
sudo: required
services:
  - docker

matrix:
  include:
    - os: linux
      before_install:
        - ./MDI_Mechanic/scripts/.travis/travis_before_install.sh
      install:
        - ./MDI_Mechanic/scripts/.internal/travis_install.sh
      before_script:
        - ./MDI_Mechanic/scripts/.internal/configure_travis.sh
      script:
        #- |
        #  if ./MDI_Mechanic/scripts/.travis/travis_script.sh ; then
        #    echo "Report script succeeded."
        #    export MDI_REPORT_STATUS=0
        #  else
        #    echo "Report script failed."
        #    export MDI_REPORT_STATUS=1
        #  fi

        # Push any changes to the report
        #- ./MDI_Mechanic/scripts/.internal/push_changes.sh
        - ./MDI_Mechanic/scripts/.travis/travis_script.sh
