language: python
python:
  - "3.6"
sudo: required
services:
  - docker

matrix:
  include:
    - os: linux
      before_install:
        - .travis/travis_before_install.sh
      install:
        - .travis/travis_install.sh
      before_script:
        - .travis/travis_before_script.sh
      script:
        - .travis/travis_script.sh
      after_success:
        - .travis/travis_after_success.sh
      after_failure:
        - .travis/travis_after_failure.sh
      after_script:
        - .travis/travis_after_script.sh
