language: cpp
python:
  - "3.6"
sudo: required
services:
  - docker

matrix:
  include:
    - os: linux
      before_install:
        # Update apt-get
        - sudo apt-get update

        # Install conda
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH=$HOME/miniconda/bin:$PATH
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a

        # Install pymdi
        - conda install -c conda-forge pymdi pyyaml pandas python-graphviz
      install:
        - ./MDI_Mechanic/scripts/.internal/travis_install.sh
      before_script:
        - ./MDI_Mechanic/scripts/.internal/configure_travis.sh
      script:
        - echo "Script"
        - |
          if python ./MDI_Mechanic/scripts/generate_report.py ; then
            echo "Report script succeeded."
            export MDI_REPORT_STATUS=0
          else
            echo "Report script failed."
            export MDI_REPORT_STATUS=1
          fi

        # Push any changes to the report
        - ./MDI_Mechanic/scripts/.internal/push_changes.sh
