language: cpp
sudo: required

matrix:
  include:
    - os: linux
      before_install:
        - echo "Before install"
      install:
        - echo "Install"
      script:
        - echo "Script"
        - ./.travis/tutorial.sh
    #- os: linux
    #  compiler: gcc
    #  env: 
    #    - LAMMPS_INSTALL="mpi"
    #    - TESTS=""
    #- os: osx
    #  addons:
    #    apt_packages:
    #      - gfortran
    #  env: 
    #    - LAMMPS_INSTALL="serial"
    #    - TESTS="not mpi"
    #- os: osx
    #  addons:
    #    apt_packages:
    #      - gfortran
    #  env: 
    #    - LAMMPS_INSTALL="serial"
    #    - TESTS="not mpi"
    #    - MPI=openmpi

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get install gfortran
        sudo apt-get install mpich libmpich-dev
        sudo pip install mpi4py
        sudo pip install numpy
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update > /dev/null
      if [ "$MPI" != "" ]; then
         brew install $MPI
      fi
    fi
  - export FC=gfortran
  - sudo pip install -U pytest pytest-cov

install:
  - BASE_PATH=$(pwd)
  - echo ${BASE_PATH}
  

script:
  - ls
  - echo "Finished script"

