version: '3'

services:
  mdi_mechanic:
    #build: .
    image: "mdi_mechanic/mdi_mechanic"
    volumes:
      - ../../../:/repo
    networks:
      mdinet:
        aliases:
          - driverhost
    depends_on:
      - engine
  engine:
    #build: ../../user
    image: "mdi_mechanic/lammps"
    volumes:
      - ../../../:/repo
    networks:
      mdinet:
        aliases:
          - enginehost

networks:
  mdinet:
    driver: "bridge"